# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lawhorn.Cloud
email: Bryan@Lawhorn.Cloud
description: >- # this means to ignore newlines until "baseurl:"
Welcome to the active learning project, "Lawhorn.Cloud" by Bryan Lawhorn!  This is a work in progress, and eventually will become a "<a href="https://www.digitalocean.com/community/tutorials/what-is-high-availability">highly available</a>" website.  Please excuse the mess while it is under construction. :)  If you would like to learn more about me, you can visit my LinkedIn page <a href="https://www.linkedin.com/in/bryanlawhorn">here</a>.  Thank you for visiting!  -Bryan
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lawhorn.cloud" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bryanlawhorn
github_username:  bryanlawhorn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
